[[redirects]]
  from = "/ts"
  to = "/.netlify/functions/ts"
  status = 200

[[redirects]]
  from = "/ip"
  to = "/.netlify/functions/ip"
  status = 200

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

[[redirects]]
  from = "/"
  to = "/.netlify/functions/home"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/notfound"
  status = 404
